/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java_agent;

import Entity.DataSet;
import Entity.DescriptorType;
import Entity.Flag;
import Package.GetClass;
import repo.DataSetRepo;
import repo.DataSetRepoMemory;

import java.io.IOException;

import java.lang.String;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;

public class App {

    static DataSetRepo taskRepository = new DataSetRepoMemory();
    public static void getclassandgetmethod(){
        //        db
        Scanner sc = new Scanner(System.in);

//        DataSet data = GetClass.getClass("Sample/KoreaSoccerPlayer");

//        String ClassName = sc.next();

        String ClassName = "Package.MyClassVisitor";

        while(true)
        {
            if (ClassName == "java.lang.Object" || ClassName == null )
            {
                break;
            }
            DataSet data = null;
            try {
                data = GetClass.getClass(ClassName);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            taskRepository.save(data);
            ClassName = data.getSuper_class();


        }

        List<DataSet> data = taskRepository.find_all();

        Collections.reverse(data);
        String tab = "\t";





    }


    public static void main(String[] args) throws IOException {

        Flag flag = new Flag();
        String ClassName = "org.objectweb.asm.ClassVisitor";
        //DescriptorType descriptorType = new DescriptorType();
        //System.out.println(descriptorType.getDescriptorType("(Ljava/lang/CharSequence;B;[[Ljava/lang/CharSequence;)Ljava/lang/String;"));

        DataSet data = GetClass.getClass(ClassName);
        taskRepository.save(data);
        data.printDataset();

        Scanner sc = new Scanner(System.in);
        String methodName = sc.next();

    }
}

