version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.37
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 5778:5778
      - 16686:16686
      # frontend
      - 4317:4317
      # gRPC OTLP
      - 4318:4318
      # HTTP OTLP
      - 14250:14250
      - 14268:14268 
      - 14269:14269
      - 9411:9411
      - 6831:6831/udp
      - 6832:6832/udp
