version: "3.8"

services:
#  jaeger:
#    image: jaegertracing/all-in-one:1.37
#    environment:
#      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
#      - COLLECTOR_OTLP_ENABLED=true
#    ports:
#      - 5778:5778
#      - 16686:16686
#      # frontend
#      - 4317:4317
#      # gRPC OTLP
#      - 4318:4318
#      # HTTP OTLP
#      - 14250:14250
#      - 14268:14268
#      - 14269:14269
#      - 9411:9411
#      - 6831:6831/udp
#      - 6832:6832/udp
  # db:
  #   image: mysql:latest
  #   environment: 
  #     MYSQL_ROOT_PASSWORD: 1234
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: 1234
  #   ports:
  #           - "3306:3306"
  #   volumes:
  #           - "./db:/docker-entrypoint-initdb.d"
  #   restart: always
  tomcat:
    container_name: tomcat11
    # image: tomcat:jdk11-openjdk
    build: 
      context: ./tomcat
      dockerfile: ./dockerfile
#    environment:
#      - JAVA_OPTS= -javaagent:./javaExporter/build/libs/javaExporter-1.0-SNAPSHOT.jar
    #         JDBC_URL: jdbc:mysql://db:3306/test?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    #         JDBC_USER: user
    #         JDBC_PASS: 1234
    ports:
            - "80:8080"
    # volumes:
    #         - ./tomcat/conf:/usr/local/tomcat/conf
    #         - ./tomcat/logs:/usr/local/tomcat/logs
    #         - ./tomcat/webapps:/usr/local/tomcat/webapps
    # links:
    #         - db
    restart: always  
