/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Agent;

import Repository.DataSetRepo;
import Repository.DataSetRepoMemory;
import java.lang.instrument.*;

import java.lang.String;


public class App {

    public static DataSetRepo taskRepository = new DataSetRepoMemory();


    public static void premain(String args, Instrumentation instrumentation) {
        System.out.println("[Permain agent] ");
        instrumentation.addTransformer(new MyClassFileTransformer());
    }

}

