spring:
  influxdb:
    url: http://localhost:8086
    username: admin
    password: admin
    database: OsData
    retention-policy: autogen
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher