spring:
  influxdb:
    url: http://localhost:8086
    username: admin
    password: admin
    database: OsData
    retention-policy: autogen
  influxdbRepo:
    cpu-table:
      name: CpuInfo
      tag: uid
      usage: cpuUsage
    disk-table:
      name: DiskInfo
      tagKey: uid
      usage: diskUsage
    mem-table:
      name: MemInfo
      tag: uid
      usage: memUsage
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher