spring:
  influxdb:
    url: http://localhost:8086
    username: root
    password: root
    database: OsData
    retention-policy: autogen
  influxdbRepo:
    cpu-table:
      name: CpuInfo
      tag: uid
    disk-table:
      name: DiskInfo
      tagKey: uid
    mem-table:
      name: MemInfo
      tag: uid
    server-table:
      name: ServerInfo
      tag: uid
    process-table:
      name: ProcessInfo
      tag: uid
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher